### ISSUE TITLE
load data failure, retun nil

### ISSUE THREAD

**Issue by he0871** [kuroko1t/gdeep#1]
sorry, my bad please close this issue! Your code is great!

**Comment by kuroko1t** [comment]
Thanks!! and sorry for my late relpy.
i have several question.
1. Did you run 'go get github.com/kuroko1t/GoMNIST' for load Mnist library?
2. Did you use example/mlpMnist.go?
3. Which code returns nil? GoMNIST.Load("./data") ?

**Comment by kuroko1t** [comment]
thank you
